/**
 * GENERATED by scripts/generate-audio.ts — do not edit by hand.
 *
 * Maps each cache key in src/core/phrases.ts to its bundled mp3 (a Metro asset
 * id from `require`). An empty map means the phrases have not been generated on
 * this checkout (needs ELEVENLABS_API_KEY + ELEVENLABS_VOICE_ID); the
 * SpeechService then falls back to expo-speech for every phrase and the
 * DebugPanel shows `expo-speech` as the backend. Run `npm run gen:audio`.
 */
export const AUDIO_MANIFEST: Readonly<Record<string, number>> = Object.freeze({});

export const AUDIO_MANIFEST_META = Object.freeze({
  generatedAt: null as string | null,
  voiceId: null as string | null,
  model: 'eleven_flash_v2_5',
  count: 0,
});
