/**
 * Non-speech clips for the audio channel manager (src/core/audio.ts).
 * Generated by scripts/generate-tones.ts (deterministic WAV, no key needed).
 * Static `require`s so Metro bundles them.
 */
/* eslint-disable @typescript-eslint/no-require-imports */
export const BEACON_L: number = require('./beacon_L.wav');
export const BEACON_R: number = require('./beacon_R.wav');
export const TICK: number = require('./tick.wav');
export const LISTEN: number = require('./listen.wav');
export const SENT: number = require('./sent.wav');
